### ISSUE TITLE
Question 3 avec question 2 ?

### ISSUE THREAD

**Issue by chaputan** [PolytechLyon/isi3-tp2-visiteur-chaput-cottet-tp2#1]
Bonjour,

Quelle est la différence entre la question 2 et la question 3 du TP ? La question 2 demande justement de définir plusieurs visiteurs, dont le postfixe. Son parcours donne la notation.

Merci par avance

**Comment by Slashgear** [comment]
Pas de vrai différence. Ce que je souhaite voir dans le rapport c'est votre compréhension du pattern
