### ISSUE TITLE
Code review needed

### ISSUE THREAD

**Issue by clement-cottet** [PolytechLyon/isi3-tp2-visiteur-chaput-cottet-tp2#2]
Bonjour Monsieur,
Pouvez-vous nous donner votre avis sur notre code ainsi que notre rapport.
En vous remerciant par avance.

**Comment by Slashgear** [comment]
- c'est très bien déjà 👍  Good Job

Je vois que ces petits retours:

- `getOpG`c'est pas très sympa comme nom. Il y a pas mal de nomage à retravailler. Exercez-vous à bien nommer les choses ici.

- La gestion de la priorité est très bien mais on évite les "magic numbers" On peut surement créer une constante, un ENUM valué, quelque chose de plus élégant et maintenable que `return 2;`
https://github.com/PolytechLyon/isi3-tp2-visiteur-chaput-cottet-tp2/blob/06b044f04e6e21119f1e120de1a693ce9af6530d/src/main/java/Addition.java#L16-L19

**Comment by chaputan** [comment]
Bonjour,
Le nommage a été effectué sur certaines méthodes et classes, et une énumération avec attribut a été appliqué pour le système de la priorité 
https://github.com/PolytechLyon/isi3-tp2-visiteur-chaput-cottet-tp2/blob/master/src/main/java/Priority.java

**Comment by Slashgear** [comment]
👌 

Vous voyez, c'est plus lisible la 😄
